version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: evaluacion3_frontend
    ports:
      - "80:3000"
    environment:
      DB_HOST: rds-cruzazul-eval3.xxxxx.us-east-1.rds.amazonaws.com
      DB_USER: user_cruzazul
      DB_PASSWORD: PassCruzAzul123!
      DB_NAME: cruzazul_db
      DB_PORT: 5432
    depends_on:
      - backend
    networks:
      - eval3-net

  backend:
    build: ./backend
    container_name: evaluacion3_backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: rds-cruzazul-eval3.cs6ze95fbgcm.us-east-1.rds.amazonaws.com
      DB_USER: user_cruzazul
      DB_PASSWORD: PassCruzAzul123!
      DB_NAME: cruzazul_db
      DB_PORT: 5432
    networks:
      - eval3-net

networks:
  eval3-net:
    driver: bridge
